per_page: 10
books:
  page: 10
  size: "200x250"
  url: "/assets/a4.jpg"

admin:
  books:
    page: 10
    size: "150x150"
    url: "/assets/dac-nhan-tam.jpg"
    pic_size: 5
  detail_width: "100%"
  users:
    size: "70x70"
    url: "assets/avata.jpg"
